### ISSUE TITLE
BUG with select all checkbox

### ISSUE THREAD

**Issue by HabelC** [bithost-gmbh/ngx-mat-select-search#336] opened 2021-08-20 09:09 UTC
**Describe the bug**
Checkbox "Select all / unselect all" is checked even if not all list elements are checked

**To Reproduce**
https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example
1. click in "Tooltip on the Select All Checkbox"
2. type "J"
2. click checkbox "Select all / unselect all" -> "Bank J (Italy)" and checkbox "Select all / unselect all" is checked
3. close list by clicking outside
4. click in "Tooltip on the Select All Checkbox" 
5. ERROR -> checkbox "Select all / unselect all" is checked, although only "Bank J (Italy)" is checked

**Expected behavior**
Checkbox "Select all / unselect all" shouldn't be checked

**Screenshots**

**Desktop (please complete the following information):**
 OS: Windows 10
 Browser Google Chrome
 Version 92.0.4515.159

**Smartphone (please complete the following information):**

**Additional context**

**Comment by macjohnny** [comment] 2021-08-20 09:11
duplicate of https://github.com/bithost-gmbh/ngx-mat-select-search/issues/219

**Comment by macjohnny** [comment] 2021-08-20 09:24
do you want to fix the examples?

**Comment by HabelC** [comment] 2021-08-31 06:07
I only mentioned the examples, because it's the same behavior as in my application. 

As you can see below, I added [toggleAllCheckboxChecked]="allSelectedChecked.locations" to my ngx-mat-select-search. 
For test purposes I added (focus)="onFocusFilter()" to my mat-select with a console.log('----- onFocusFilter() this.allSelectedChecked', this.allSelectedChecked['locations']);
Even if this.allSelectedChecked['locations'] is false, the all checkbox is checked.

<mat-select multiple (focus)="onFocusFilter()"
            [ngModel]="inputFields?.locations"
            (ngModelChange)="inputFields.locations = $event; filtersChanged()">
  <mat-option>
    <ngx-mat-select-search [showToggleAllCheckbox]="true" (toggleAll)="toggleAllSelection($event, 'locations'); filtersChanged()"
                           [toggleAllCheckboxChecked]="allSelectedChecked.locations"
                           [toggleAllCheckboxTooltipMessage]="translations?.selectUnselectAll" [toogleAllCheckboxTooltipPosition]="'above'"
                           [alwaysRestoreSelectedOptionsMulti]="true" [formControl]="locationFilterCtrl"
                           placeholderLabel="{{ translations?.search }}" noEntriesFoundLabel="{{ translations?.noResultsFound }}">
      <mat-icon ngxMatSelectSearchClear>clear</mat-icon>
    </ngx-mat-select-search>
  </mat-option>
  <mat-option *ngFor="let location of filterOptionsFiltered?.locations"
              [value]="location?.id">
    {{ location?.name }}
  </mat-option>
</mat-select>

**Comment by AhsanAyaz** [comment] 2022-10-09 10:49
@macjohnny  can you mark this issue for `hacktoberfest`?  Thanks

**Comment by macjohnny** [comment] 2022-10-10 07:34
@AhsanAyaz I added the topic "hacktoberfest" to this repo, this should be enough, right?

**Closed** 2022-10-10 11:18 UTC
Labels: examples, hacktoberfest

**Comment by AhsanAyaz** [comment] 2022-10-11 00:01
@macjohnny , yeah I believe so!
And thanks 🙂
