### ISSUE TITLE
First dropdown of the page doesn't work

### ISSUE THREAD

**Issue by shashikantdurge** [bithost-gmbh/ngx-mat-select-search#82] opened 2018-12-01 06:44 UTC
Only First dropdown:
1.  auto selects the first value of the dropdown.
2.  search works, but Enter key doesn't selects the option.

**Comment by macjohnny** [comment] 2018-12-01 08:49
@shashikantdurge thanks for opening this issue. unfortunately, I am not able to reproduce the problems you described with the example https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example

The first dropdown correctly sets the first item of the filtered list active and selecting the option with the enter key works.

Which version are you using? Can you provide an example code or preferrably a working example on stackblitz? You can use https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example as a starting point.

**Comment by macjohnny** [comment] 2018-12-10 16:02
Since we are unable to reproduce the issue, i am closing this for now.
@shashikantdurge if you still think this is a valid issue, please provide more details about what exactly the problem is and how to reproduce it. I will re-open the issue then.

**Closed by macjohnny** 2018-12-10 16:02 UTC
Labels: question
