### ISSUE TITLE
[BUG]Adding items to an existing list will cause MatSelect to scrollToTop = 0.

### ISSUE THREAD

**Issue by jvinhit** [bithost-gmbh/ngx-mat-select-search#207] opened 2020-02-10 04:38 UTC
**Describe the bug**

When update dataSource ( push new item to list ) mat-select scrollTop = 0;
When debugger check problem in here:

``` javascript
 /**
   * Scrolls the currently active option into the view if it is not yet visible.
   */
private adjustScrollTopToFitActiveOptionIntoView(): void {
    if (this.matSelect.panel && this.matSelect.options.length > 0) {
      const matOptionHeight = this.getMatOptionHeight();
      const activeOptionIndex = this.matSelect._keyManager.activeItemIndex || 0;
      const labelCount = _countGroupLabelsBeforeOption(activeOptionIndex, this.matSelect.options, this.matSelect.optionGroups);
      // If the component is in a MatOption, the activeItemIndex will be offset by one.
      const indexOfOptionToFitIntoView = (this.matOption ? -1 : 0) + labelCount + activeOptionIndex;
      const currentScrollTop = this.matSelect.panel.nativeElement.scrollTop;

      const searchInputHeight = this.innerSelectSearch.nativeElement.offsetHeight
      const amountOfVisibleOptions = Math.floor((SELECT_PANEL_MAX_HEIGHT - searchInputHeight) / matOptionHeight);

      const indexOfFirstVisibleOption = Math.round((currentScrollTop + searchInputHeight) / matOptionHeight) - 1;

      if (indexOfFirstVisibleOption >= indexOfOptionToFitIntoView) { ==>> bug indexOfOptionToFitIntoView = 0
        this.matSelect.panel.nativeElement.scrollTop = indexOfOptionToFitIntoView * matOptionHeight;
      } else if (indexOfFirstVisibleOption + amountOfVisibleOptions <= indexOfOptionToFitIntoView) {
        this.matSelect.panel.nativeElement.scrollTop = (indexOfOptionToFitIntoView + 1) * matOptionHeight - (SELECT_PANEL_MAX_HEIGHT - searchInputHeight);
      }
    }
  }
```
issue in conditional : `if (indexOfFirstVisibleOption >= indexOfOptionToFitIntoView) `
**To Reproduce**

*Important* Please provide a reproduction example. You can use https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example as a starting point

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by macjohnny** [comment] 2020-02-10 06:54
@jvinhit thanks for reporting this issue.
I think this is a duplicate of https://github.com/bithost-gmbh/ngx-mat-select-search/issues/200, so let's continue the discussion there and close this one.

**Closed by macjohnny** 2020-02-10 06:54 UTC
Labels: bug
