### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by tu-hai** [bithost-gmbh/ngx-mat-select-search#406] opened 2022-11-18 02:36 UTC
**Is your feature request related to a problem? Please describe.**

Update or Support Angular Material version 15
**Describe the solution you'd like**

Update or Support Angular Material version 15
**Describe alternatives you've considered**

Update or Support Angular Material version 15
**Additional context**

Update or Support Angular Material version 15

**Comment by macjohnny** [comment] 2022-11-18 06:54
Duplicate of https://github.com/bithost-gmbh/ngx-mat-select-search/issues/395

**Closed by macjohnny** 2022-11-18 06:54 UTC
Labels: enhancement
