### ISSUE TITLE
[BUG] : The currently selected option hidden under the search input field

### ISSUE THREAD

**Issue by Supriya-bansal** [bithost-gmbh/ngx-mat-select-search#302] opened 2021-01-31 14:18 UTC
The currently selected option hidden under the search input field when opening the options panel.

When we have a default value selected for the dropdown, focusing search input hides the selected option behind the input and hence not visible to the user. On the contrary it would be nice for the user if the selected option is visible on opening the panel.

**Comment by macjohnny** [comment] 2021-02-01 08:51
@Supriya-bansal could you please provide a demo with your code e.g. on stackblitz.com?

does your issue also occur in the example https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example ?
if so, what are the steps to reproduce it?

**Comment by macjohnny** [comment] 2021-02-17 12:51
can't reproduce, closing the issue
@Supriya-bansal if you still encounter this issue, please provide reproduction steps and an example, so I can re-open this issue.

**Closed by macjohnny** 2021-02-17 12:51 UTC
Labels: bug
