### ISSUE TITLE
How can I pre-select values in app-multiple-selection-select-all-example

### ISSUE THREAD

**Issue by kumaroswal** [bithost-gmbh/ngx-mat-select-search#184] opened 2019-11-04 01:56 UTC
Can I pre-select values in app-multiple-selection-select-all-example.
If I am using it on an add/edit form, then I will need the above functionality in edit mode for sure.

I apologize in advance if this may not be the right place to ask this particular question.

**Comment by macjohnny** [comment] 2019-11-04 06:35
see https://github.com/bithost-gmbh/ngx-mat-select-search/issues/96#issuecomment-453016659
does that solve your problem?

**Comment by kumaroswal** [comment] 2019-11-10 23:19
another question before i can apply the above solution.
I am getting the below error while implementing the 
`app-multiple-selection-select-all-example`
![image](https://user-images.githubusercontent.com/382487/68552549-024cfb80-03cd-11ea-82d2-1b49232fccfd.png)

**Comment by kumaroswal** [comment] 2019-11-11 02:16
I self-answered the above question. I am on Angular 7.x. 
`static: true` is supported by Angular 8 and plus only. 
If we want this widget to be backward compatible then either remove this option or add a comment in there for the same.

**Comment by macjohnny** [comment] 2019-11-11 05:46
For angular 7 compatibility, please use version. 1.8.0, see https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/README.md#compatibility

**Comment by kumaroswal** [comment] 2019-11-12 01:16
Thanks Macjohnny.

More questions please a I keep using it deeper.

How can I include multiple fields in the search?
`this.filteredBanksMulti.next(
       this.banks.filter(bank => bank.name.toLowerCase().indexOf(search) > -1)
     );`. 
Example :- I want to include `bank.number` and `bank.areaCode` in the above search too.

**Comment by macjohnny** [comment] 2019-11-12 05:46
Just adapt your client code:
this.banks.filter(bank => bank.name.toLowerCase().indexOf(search) > -1 || String(bank.areaCode).toLowerCase().indexOf(search) > -1)

**Comment by macjohnny** [comment] 2019-11-12 06:51
I am closing this issue, as it is not a bug or feature request. You can still comment in this issue.

**Closed by macjohnny** 2019-11-12 06:51 UTC
Labels: question

**Comment by kumaroswal** [comment] 2019-11-13 00:49
@macjohnny I am trying to change the background color of the checkboxes within the dropdowns when they are checked. But seems it not allowing me. Also need to change the font color of mat-options when they are selected. I also need to make sure that the dropdown when triggered should open below the current clicked element, is that achievable here?

`mat-option .mat-pseudo-checkbox-checked {
    background-color: #FDB913;
}`

**Comment by kumaroswal** [comment] 2019-11-27 04:36
Hey @macjohnny .
Another question for you please on the searching part.
How can I make the search to work with a combination of multiple fields? With the above suggestion you made it just searches by one of those fields but not a combination of both.

**Comment by macjohnny** [comment] 2019-11-27 05:45
You could split the keyword by the space character and loop through all fields you want to search

**Comment by kumaroswal** [comment] 2019-11-27 10:47
@macjohnny Didnt quite understand. Can you give a code example please. Thanks.

**Comment by macjohnny** [comment] 2019-11-27 11:21
searchKeyword.split(' ')

**Comment by kumaroswal** [comment] 2019-11-27 13:15
@macjohnny 
So how would I use your recommendation in this case please - 
`this.filteredEmployees.next(
          this.dpEmployees.filter(employee => (employee.Number.toLowerCase().indexOf(search) > -1 ||
          employee.FirstName.toLowerCase().indexOf(search) > -1 ||
          employee.LastName.toLowerCase().indexOf(search) > -1))
        );`

**Comment by macjohnny** [comment] 2019-11-27 15:36
Const keywordParts = searchKeyword.split(„ „)
this.filteredEmployees.next( this.dpEmployees.filter(employee => keywordParts.some(keyword => (employee.Number.toLowerCase().indexOf(keyword) > -1) || keywordParts.some(keyword =>  employee.FirstName.toLowerCase().indexOf(keyword) > -1) || keywordParts.some(keyword =>  employee.LastName.toLowerCase().indexOf(keyword) > -1))) );

**Comment by kumaroswal** [comment] 2019-12-02 07:01
thanks
