### ISSUE TITLE
[BUG] - Previously selected options getting deselect if modify the search

### ISSUE THREAD

**Issue by gurjar-prasad** [bithost-gmbh/ngx-mat-select-search#270] opened 2020-10-23 12:35 UTC
Describe the bug:
Previously selected options getting deselect if modify the search

To Reproduce:

Go to https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example
Scroll down to 'Multiple selection with Select All Checkbox'
Enter 'Bank C' in search
Click the select 'Bank C'
Select text 'Bank C' from search by double click on whole text or backspace and Change to 'Bank F'
Click the select 'Bank F'
Note the previously selected options have been removed

Expected behavior:
I expect Bank F should get selected from the list of options, with none of the currently selected options removed.

Addition information:
Getting this issue in: 
ngx-mat-select-search  version 3.1.0
angular-cli 10.0.5
angular-material 10.1.3

**Comment by pranavneeraj** [comment] 2020-10-23 13:00
This Can be resolved by putting the below lines in src/app/mat-select-search/mat-select-search.component.ts(Line no. 661).

-       if (this.matSelect.multiple && !value.previousValue) {
+      if (this.matSelect.multiple) {

Explanation:

The issue was occurring due to when the user does the filtering and then selects any value and then does some more filtering for another selection the if condition was failing.

**Comment by macjohnny** [comment] 2020-10-23 13:28
Thanks for reporting and proposing a solution. Would you like to file a PR?

**Comment by pranavneeraj** [comment] 2020-10-23 13:31
> Thanks for reporting and proposing a solution. Would you like to file a PR?

Yes, But for filing PR will need permission for the repo. Thanks

**Comment by pravin23pawar** [comment] 2020-10-23 13:44
We are also facing the same problem and the above proposed solution seems to work with our problem too.
Please response. Thanks for your help.

**Comment by macjohnny** [comment] 2020-10-23 14:05
@pranavneeraj you can simply fork this repo, create a branch with the fix in the forked repo, and file a PR against the original repo

**Comment by pranavneeraj** [comment] 2020-10-23 14:12
@macjohnny Please check https://github.com/bithost-gmbh/ngx-mat-select-search/pull/271.

**Comment by macjohnny** [comment] 2020-10-23 14:53
@pranavneeraj somehow I am unable to reproduce  the issue:


[ngx-mat-select-search-issue-270.webm.zip](https://github.com/bithost-gmbh/ngx-mat-select-search/files/5430189/ngx-mat-select-search-issue-270.webm.zip)

can you please post a screen video of the reproduction steps?

**Comment by pranavneeraj** [comment] 2020-10-23 15:03
@macjohnny Please refer below recording for reference.
[bug_repr.zip](https://github.com/bithost-gmbh/ngx-mat-select-search/files/5430250/bug_repr.zip)

**Comment by macjohnny** [comment] 2020-10-23 15:17
thanks for the screen video, I can now reproduce the issue.

**Closed** 2020-10-23 15:54 UTC
Labels: bug

**Comment by macjohnny** [comment] 2020-10-23 16:03
the fix was release with version 3.1.2
thanks for reporting and trying to fix it!

**Comment by pranavneeraj** [comment] 2020-10-23 16:55
> the fix was released with version `3.1.2`
> thanks for reporting and trying to fix it!

Thanks for your quick response.
