### ISSUE TITLE
Pressing tab on control moves focus to body

### ISSUE THREAD

**Issue by arishu39** [bithost-gmbh/ngx-mat-select-search#52] opened 2018-08-22 15:42 UTC
I tested it for multi-select. Whenever the dropdown is open, the focus is always on search input field. Whenever we press tab on that the focus moves on to 'body' rather than next element. this is causing accessibility issue. Could you please look into this.

**Comment by arishu39** [comment] 2018-08-22 16:27
This issue is only present in material version 5.2.4. It works fine with 6.0.0. Could you please fix it for 5.2.4?

**Comment by macjohnny** [comment] 2018-08-23 05:33
@arishu39 thanks for the bug report. Since this works correctly with material 6.0.0, where the original issue was resolved (see https://github.com/angular/material2/blob/master/CHANGELOG.md#bug-fixes-15 and https://github.com/angular/material2/issues/10900), I think it is safe to say this is not a bug in `ngx-mat-select-search`, therefore I close this issue.

However, if you can't update to the newest `^6.0.0` release, as a workaround, if you look at the changes that fixed the bug (https://github.com/angular/material2/pull/10905/files#diff-102eaa94de98ed2cabd87565ba514125R829), you could do something like
```
myMatSelectField._keyManager.tabOut.pipe(takeUntil(this._destroy)).subscribe(() => {
      // Restore focus to the trigger manually
      // TODO: remove me when upgrading to material 6.x.x
      myMatSelectField.focus();
    });
```

**Closed by macjohnny** 2018-08-23 05:33 UTC
Labels: not a bug

**Comment by arishu39** [comment] 2018-08-23 07:34
Thanks a lot Esteban. I really appreciate your quick response on this.

**Comment by macjohnny** [comment] 2018-08-23 08:37
@arishu39 you are welcome. if you like the project, feel free to star in here on github.
