### ISSUE TITLE
Adding items to an existing list will cause MatSelect to scroll to first item.

### ISSUE THREAD

**Issue by ArsalanSavand** [bithost-gmbh/ngx-mat-select-search#200] opened 2019-12-13 22:23 UTC
I'm having a list of items and searching with server client.
I'm using a library to load more items once user reaches bottom of the scroll container. Problem is when I push new items to my list, it scrolls to first item.

The problem is not with the library I'm using, because even if I just randomly push an item to my list, it happens.

**Comment by macjohnny** [comment] 2019-12-14 07:12
Can you please provide a stackblitz demo?

**Comment by nprasovict** [comment] 2019-12-18 20:27
I'm using ng-mat-select-infinite-scroll component and have noticed the same behavior.

Here is working [stackblitz](https://stackblitz.com/edit/ng-mat-select-infinite-scroll-3a3kbc?file=src%2Fapp%2Fapp.component.html)

If you remove ngx-mat-select-search from app.component.html and reload browser view on the right, options list will not jump to start after you scroll to the end and infinite scroller adds new items to it.

If you leave ngx-mat-select-search as is in the app.component.html, every time you scroll to the end of options and infinite scroller loads a new batch of items, the list jumps to start.

**Comment by macjohnny** [comment] 2019-12-19 09:40
thanks for the example.
I think the problem is here
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/4138c7523db4b580bb641840d08331808e14a781/src/app/mat-select-search/mat-select-search.component.ts#L281-L290

this is needed to scroll to the first option of the filtered result. Somehow we should distinguish why the options changed, due to search or due to additional loading.

**Comment by macjohnny** [comment] 2019-12-19 09:58
a first fix for this could be to add an input to disable this behavior. @nprasovict @ArsalanSavand would you like to investigate this and find a fix?

**Comment by nprasovict** [comment] 2019-12-23 14:52
I won't have time to work on this since my team decided to go with different UX design where we don't use drop-down lists and hence won't be using ngx-mat-select-search and ng-mat-select-infinite-scroll.

**Comment by macjohnny** [comment] 2020-02-07 08:05
this issue is also reproducible in the demo by @L-NiNo: https://stackblitz.com/edit/mat-select-search-with-infinity-scroll

**Comment by macjohnny** [comment] 2020-02-10 07:15
@jvinhit would you like to give it a try and find a fix?

**Comment by ChristopherKiss** [comment] 2020-03-03 01:25
@macjohnny,

I've opened a PR to fix this issue. https://github.com/bithost-gmbh/ngx-mat-select-search/pull/214

**Comment by vladimir-poma** [comment] 2020-03-12 20:45
This is the first time that I do a workaround like this, but I could be able to solve this by overwriting for a moment the **setFirstItemActive** function when you update your list, to avoid autoscrolling by doing

```html
<mat-form-field>
          <mat-select [(value)]="itemSelected">
            <mat-option>
              <ngx-mat-select-search
                #singleSelect
                [formControl]="filterCtrl"
                placeholderLabel="select an item">
                <mat-icon ngxMatSelectSearchClear>x</mat-icon>
              </ngx-mat-select-search>
            </mat-option>
            <mat-option
              *ngFor="let option of options"
              [value]="option._id">
              {{option.name}}
            </mat-option>
          </mat-select>
</mat-form-field>
```

```javascript
import { MatSelect } from '@angular/material/select';
// other imports

@Component({
})
export class YourComponent implements OnInit, OnDestroy {
  options: [];
  @ViewChild('singleSelect', {static: false}) singleSelect: MatSelect;
  constructor(/**/) {
    // ...
  }

  updateList() {
    // custom service request
    this.service.request().subscribe(response) => {
       // backuping in another variable setFirstItemActive fn
       this.singleSelect.matSelect._keyManager.setFirstItemActivebk = this.singleSelect.matSelect._keyManager.setFirstItemActive;
       this.singleSelect.matSelect._keyManager.setFirstItemActive = () => {};
       
       this.options = this.options.concat(response['body']); // updating the options

       // restoring setFirstItemActive fn
       setTimeout(() => {
         this.singleSelect.matSelect._keyManager..setFirstItemActive = this.singleSelect.matSelect._keyManager.setFirstItemActivebk;
       }, 100);
    })
  }
}

```

I hope someone could figure out a proper way to solve this, in the meanwhile maybe this solution can help someone :)

**Comment by raysuelzer** [comment] 2020-06-11 03:32
I'm working on a fix to this.  

Essentially, you should only need to call `keymanager.setFirstItemActive()` if the current firstItem in the options list changes...

**Comment by TheParad0X** [comment] 2020-06-12 09:07
Thank you

**Closed** 2020-06-16 06:03 UTC
Labels: bug

**Comment by GreyM22** [comment] 2021-07-14 15:23
I tried the solution to this issue and it didn't work.  The solution given by `vladimir-poma` has syntax error and it seems like he didnt even test it. It didnt work and it keeps scrolling on top. Please can some one tell if there is a way to stop the scrolling of the mat select when you add new data?

**Comment by JustinAtanasiu** [comment] 2021-09-21 19:59
@GreyM22  I just had this problem and I think I found a solution.

Looks like the jump is triggered by `adjustScrollTopToFitActiveOptionIntoView`: [https://github.com/bithost-gmbh/ngx-mat-select-search/blob/4138c7523db4b580bb641840d08331808e14a781/src/app/mat-select-search/mat-select-search.component.ts#L571-L591](url)

This can be solved by calling: `this.matSelect._keyManager.setActiveItem(index)` after items were added to the list. The index can be computed if you know how many items were in the list prior to adding more.

**Comment by lorespaul** [comment] 2021-12-17 15:52
After setting property "disableScrollToActiveOnOptionsChanged" to true problem is solved

`          
            <ngx-mat-select-search
                [formControl]="searchCtrl"
                [disableScrollToActiveOnOptionsChanged]="true"
                placeholderLabel="Search"
                noEntriesFoundLabel="No entry">
            </ngx-mat-select-search>
`
