### ISSUE TITLE
In multiselect, (selectionChange) event of the control does not contain all the elements but just the newly selected

### ISSUE THREAD

**Issue by macjohnny** [bithost-gmbh/ngx-mat-select-search#387] opened 2022-07-14 16:18 UTC
Hey, this fix just broke my behavior! By modifying a copy of values but not the original one the `(selectionChange)` event of the control does not contain all the elements but just the newly selected.

@qstiegler Can you show me your usecase where version 4.1.1 threw an exception for you so I can maybe fix this?

_Originally posted by @angelaki in https://github.com/bithost-gmbh/ngx-mat-select-search/issues/376#issuecomment-1184489849_

**Comment by macjohnny** [comment] 2022-07-14 16:34
@angelaki sorry for the issue

so the FormControl has the correct set of selexted values but (selectionChange) does not emit the correct set?

**Comment by macjohnny** [comment] 2022-07-14 16:48
Hmm i wonder why, because in https://github.com/bithost-gmbh/ngx-mat-select-search/blob/092aaf963d2b9cb3cb36f79cab1f6d3c6f35aa63/src/app/mat-select-search/mat-select-search.component.ts#L632 we set the correct values, but maybe because those options are not present while filtering, they get deselected  (which is exactly the purpose of this workaround method, which to compensate for that)
Any suggestion how to fix that?

**Comment by angelaki** [comment] 2022-07-14 16:51
Let me check these days. Maybe you can somehow stop the even from propagation and only call the last one.

Grüße

Tristan Sprößer
________________________________

**Comment by angelaki** [comment] 2022-07-14 22:33
Ok, wow. Let's say: it's getting complicated. I made a fork to show the current misbehavior: https://github.com/angelaki/ngx-mat-select-search?organization=angelaki&organization=angelaki. The earlier version wasn't perfect at all, because the handler just manipulates the event value. It was more luck that it was the first handler called - but it somehow always is? I already tried toggling he search with *ngIf. The controls internal handler always seams to be called first. Lucky me ...

Never the less, we are already in the `valueChanges` cycle and I have no idea how to stop it without some super ugly private accesses etc. Imho the earlier solution was the best we can get. Why was it changed at all? How is it possible that @qstiegler array was readonly? Maybe we can find a solution for this. But anyway, I guess it's staying a bit quircky :/

**Comment by qstiegler** [comment] 2022-07-15 05:58
Hey guys, I'm sorry to hear about the negative side effect of the fix.

The initial error occurred when you have one or more selected, then you search for another value where the previous selected values are not part of the options anymore. When you select now the value, the previous selected values get unselected. I hope this helps.

**Comment by macjohnny** [comment] 2022-07-15 06:23
Ok so for the time being, I suggest we revert https://github.com/bithost-gmbh/ngx-mat-select-search/pull/377 and then analyze the situation of the readonly array

**Comment by angelaki** [comment] 2022-07-15 06:33
Yeah, think so,too. @qstiegler can you create a minimal reproduction of your behavior? Your description sounds like this should always happen. This just isn't the case, as you can see in the live examples: https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fapp.component.html

**Comment by qstiegler** [comment] 2022-07-15 16:02
@angelaki Puh...it took me a while today to create a working minimal reproduction but now I figured it out. 

The problem is the combination with the `NGXS` store. When you push values to the store, they get immutable. This means that the next time when you select another value and you're adding the previousSelectedValues, it tries to manipulate the same value which is marked as immutable.

Here is the link to reproduce: https://stackblitz.com/edit/angular-ivy-5dffxg?file=src/app/app.component.ts

1. Select `Option 1`
2. Search for `2`
3. Select `Option 2`
4. The console output shows the error `Cannot add property 1, object is not extensible` and only the `Option 2` is selected

I think in general if you do manipulations of the form value object, it always should be immutable, that's why I thought my solution would be good. I hope we find another one which fixes both.

As a short term solution I can create a copy of the array before I send it to the store but this is pretty prone to failure.

I hope this will help you guys!

**Closed** 2022-07-19 06:13 UTC

**Comment by qstiegler** [comment] 2022-07-19 06:26
Is there a reason why you closed it? I really hope you'll come up with an immutable solution.

**Comment by angelaki** [comment] 2022-07-19 06:31
I'll create a unit test these days, check your sample and see what we / I can do. But tbh I think it'll be quite hard.

Grüße

Tristan Sprößer
________________________________

**Comment by macjohnny** [comment] 2022-07-19 07:56
@qstiegler I reopened https://github.com/bithost-gmbh/ngx-mat-select-search/issues/376
