### ISSUE TITLE
[BUG] mouse cursor

### ISSUE THREAD

**Issue by bennoparikh** [bithost-gmbh/ngx-mat-select-search#127] opened 2019-03-22 11:37 UTC
**Describe the bug**
Mouse cursor disappears after clicking an arrow key

**To Reproduce**
1) Highlight an option by placing the mouse cursor over it.  The option is now highlighted grey.  This is ok.
2) Now click the down arrow.  The arrow option selection option is highlighted grey.  This is ok.  However the option where the mouse was over is still highlighted however the mouse cursor disappears.

**Expected behavior**
1) Either the mouse cursor stays on the screen and two highlighted options are present
2) Or the mouse cursor disappears and highlighted option where the mouse cursor was is not longer highlighted. 

**Screenshots**
In my screenshot the mouse is over "Fräulein" option.  I then click the down arrow 2 times.  Herr and Frau option is selected, however the Fräulein option stays selected.  It is confusing because the mouse cursor has disappeared.  Either the mouse cursor should stay visible with both options highlighted, or the mouse cursor disappears and the mouse cursor option is not longer highlighted.

**Desktop (please complete the following information):**

![Screenshot 2019-03-22 at 12 32 10](https://user-images.githubusercontent.com/9047575/54820177-92073380-4c9e-11e9-9143-b2baa8e69d41.png)

**Comment by macjohnny** [comment] 2019-03-22 11:46
@bennoparikh I think this is not related to `ngx-mat-select-search` but rather to `mat-select` itself.
However, I am not able to reproduce the issue. I tried with `@angular/material@7.3.5`, `ngx-mat-select-search@1.7.0`, Chrome 71, IE11

Can you create a stackblitz example?
Which versions are you using?

**Comment by bennoparikh** [comment] 2019-03-22 11:51
Hi macjohnny,  
Thanks for your quick replay.  Using mat-select without ngx-mat-select-search then the mouse cursor stays on the screen and both are highlighted.   
 "ngx-mat-select-search": "^1.7.0",
 "@angular/material": "^7.2.1",

I found a stackblitz example (not from me) that has the same problem:
https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fexamples%2F01-single-selection-example%2Fsingle-selection-example.component.html

**Comment by macjohnny** [comment] 2019-03-22 11:53
which browser are you using?

**Comment by bennoparikh** [comment] 2019-03-22 11:57
Chrome Version 72.0.3626.121 (Official Build) (64-bit)
Firefox 66.0 (64-bit)

**Comment by macjohnny** [comment] 2019-03-22 11:58
which operating system? if i try it, the cursor stays. Moreover, I can't figure out which part of the code could cause such a behavior.

**Comment by bennoparikh** [comment] 2019-03-22 11:59
macOS.  I will try it on a Windows machine.

**Comment by bennoparikh** [comment] 2019-03-22 12:01
Wow, works on Windows, but not on Mac.  :-(

**Comment by macjohnny** [comment] 2019-03-22 12:15
very strange. 
the only part in the code that handles keytrokes is here:

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/0f675b55d36c0935813b3e53a15e0a29feee8b04/src/app/mat-select-search/mat-select-search.component.ts#L335-L345

but it does not handle the arrow keys, they are simply forwarded to `mat-select`

however, it could also be due to the fact that we are focusing an input field and then hitting keys.
does the cursor also disappear when typing characters?

**Comment by bennoparikh** [comment] 2019-03-22 12:22
Yeah, cursor disappears also with other key strokes.   However with just mat-select, the cursor does not disappear.  However that is works correctly on Windows makes this not such a critical problem for us, since the end customer uses Windows and their OS.

**Comment by macjohnny** [comment] 2019-03-22 12:23
does the cursor also disappear when typing in a simple `matInput` (e.g. https://material.angular.io/components/input/overview)?

**Comment by bennoparikh** [comment] 2019-03-22 13:10
Cursor also disappears with a matInput (Mac), but not with Windows.

**Comment by macjohnny** [comment] 2019-03-22 13:12
and how about a plain `<input type="text" />` field?

**Comment by bennoparikh** [comment] 2019-03-22 13:17
yeah, mouse cursor disappears also with a plain input.

**Comment by macjohnny** [comment] 2019-03-22 13:17
ok, so I close this as it is the standard browser behavior

**Closed by macjohnny** 2019-03-22 13:17 UTC
Labels: not a bug, wontfix

**Comment by bennoparikh** [comment] 2019-03-22 13:26
Ok, now I understand the problem.  A normal html select, when pressing the arrows keys, in Mac, the mouse cursor stays.  With a normal HTML input as discussed, the cursor in Mac disappears.  That is why a mat-select has no problem with the mouse cursor, because probably just wraps a html select.  However your component probably wraps also a html input - text at that cause the difference.  Sure learned a lot today ;-).  Thanks for your time.
