### ISSUE TITLE
Setting initial value of the Multi select dropdown

### ISSUE THREAD

**Issue by harshnagalla** [bithost-gmbh/ngx-mat-select-search#96] opened 2019-01-10 08:08 UTC
I am trying to loop through an array and set the value of the FormControl dynamically but it only sets the value for the last array element 

This is what i am trying to do -
```typescript
                 for (let currentindex = 0; currentindex < indexofroles / 2; currentindex++) {
                    for (let roleindex = 0; roleindex < this.roles.length; roleindex++) {
                        if (this.data.user.userRoleDto[currentindex].roleDto.roleName === this.roles[roleindex].roleName) {
                           builder.push(this.roles[roleindex].roleName);
                            this.MultiRoleCtrl.setValue([this.roles[roleindex].roleName]);
                        }
                    }
                }
```

**Comment by macjohnny** [comment] 2019-01-10 08:50
you need to set the value after you have collected the list of values, since now you are resetting the selected value on each loop pass.
Here is how you can solve it:

```typescript
                const roleNames: string[] = [];
                for (let currentindex = 0; currentindex < indexofroles / 2; currentindex++) {
                    for (let roleindex = 0; roleindex < this.roles.length; roleindex++) {
                        if (this.data.user.userRoleDto[currentindex].roleDto.roleName === this.roles[roleindex].roleName) {
                           builder.push(this.roles[roleindex].roleName);
                           roleNames.push(this.roles[roleindex].roleName); 
                        }
                    }
                }
               this.MultiRoleCtrl.setValue(roleNames);
```
Also, make sure you set the `matSelect.compareWith` function after the options have been loaded if you load the options asynchronously, see https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/examples/02-multiple-selection-example/multiple-selection-example.component.ts#L72

Since this is not a bug, I am closing this issue.

**Closed by macjohnny** 2019-01-10 08:50 UTC
