### ISSUE TITLE
mat-select-search selecting from drop down issue 

### ISSUE THREAD

**Issue by OmarAlBchouti** [bithost-gmbh/ngx-mat-select-search#40] opened 2018-07-03 16:28 UTC
Hello,

I just npm install the ngx-mat-select-search I occurred a bug when I filter the drop-down then select an item, the item is selected, then in a moment the drop-down select the default value
Step to reproduce:

1. Filter the list  all work fine
2. Select an option  the item will be displayed as usual 
3. then in just a moment is reselecting the first item in the source list

this bug occurs only if I filter the list.
I noticed that on dropdown close the clearing of the input text is repopulated the filtered list.

Plus when the clearSearchInput  is false all work fine but when its true the problem is apparent,

Can you help me with the problem 

Regard and thanx

**Comment by macjohnny** [comment] 2018-07-04 07:03
@OmarAlBchouti which versions of `angular` / `material` / `ngx-mat-select-search` do you use?
could you provide an example on stackblitz? with the example at [https://stackblitz.com/github/llqiopmm](https://stackblitz.com/github/llqiopmm) I am unable to reproduce the bug you describe. Can you verify your bug also occurs in this example?

**Comment by OmarAlBchouti** [comment] 2018-07-04 08:44
i'm using 
angular: local version is v 6.0.1 and global angular cli version is v 6.0.8
material : v 6.3.2
and ngx-mat-select-search : v 1.2.4
and i'm using the exact same example found in the demo 
regard

**Comment by macjohnny** [comment] 2018-07-04 09:13
@OmarAlBchouti can you reproduce the bug on [https://stackblitz.com/github/llqiopmm](https://stackblitz.com/github/llqiopmm)? if so, could you try to describe the steps again that lead to the behavior?
Could you post your code?

**Comment by OmarAlBchouti** [comment] 2018-07-04 09:41
I'm using the same example found in https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example
When i select an item from the drop-down is selected 
but when i filter then select an item => the item is selected then in just a  moment is select the first item in mat-option

**Comment by macjohnny** [comment] 2018-07-04 10:20
@OmarAlBchouti I am sorry but I am unable to observe the behavior you describe if I use [https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example](https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example)
which browser are you using?
can you record your screen to show the issue?

**Comment by OmarAlBchouti** [comment] 2018-07-04 17:19
hello,
you will find below the code related you should be able to reproduce
This is the app.component.ts:
`import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
 public defaultdrop:string ="Me";
 public the: string ="no data found";
 public defaultlabel: string ="Select Value";
 
  private banks: any[] = [
    {description: 'Bank A (Switzerland)', id: 'A'},
    {description: 'Bank B (Switzerland)', id: 'B'},
    {description: 'Bank C (France)', id: 'C'},
    {description: 'Bank D (France)', id: 'D'},
    {description: 'Bank E (France)', id: 'E'},
    {description: 'Bank F (Italy)', id: 'F'},
    {description: 'Bank G (Italy)', id: 'G'},
    {description: 'Bank H (Italy)', id: 'H'},
    {description: 'Bank I (Italy)', id: 'I'},
    {description: 'Bank J (Italy)', id: 'J'},
    {description: 'Bank Kolombia (United States of America)', id: 'K'},
    {description: 'Bank L (Germany)', id: 'L'},
    {description: 'Bank M (Germany)', id: 'M'},
    {description: 'Bank N (Germany)', id: 'N'},
    {description: 'Bank O (Germany)', id: 'O'},
    {description: 'Bank P (Germany)', id: 'P'},
    {description: 'Bank Q (Germany)', id: 'Q'},
    {description: 'Bank R (Germany)', id: 'R'}
  ];
  ngOnInit() {
  }
  action(id:any){
    this.defaultdrop="employee"
  }
}`

this is the app.component.html
`<app-select 
   [list]=banks
   [dropDownPlaceHolder]=defaultdrop
   [noDataFoundLabel]=the
   [defaultDescription]=defaultlabel 
   (select)="action($event)"></app-select>`

this is the select.component.html:
`<mat-form-field>
  <mat-select [formControl]="dropDownCtrl" [ngModel]="seletecvalue" placeholder={{dropDownPlaceHolder}} (selectionChange)="changeValue($event)"
   #singleSelect>
    <ngx-mat-select-search [formControl]="dropDownFilterCtrl" [noEntriesFoundLabel]=noDataFoundLabel ></ngx-mat-select-search>
    <mat-option value='-1' >{{defaultDescription}}</mat-option>
    <mat-option *ngFor="let item of filteredList | async" [value]="item.id" >
      {{item.description}}
    </mat-option>
  </mat-select>
</mat-form-field>`

this is the select.component.ts
`import { Component, OnInit, Input, ViewChild, OnDestroy, AfterViewInit, Output ,EventEmitter} from '@angular/core';
import { MatSelect, MatSelectChange } from '@angular/material';
import { FormControl } from '@angular/forms';
import { ReplaySubject } from 'rxjs/internal/ReplaySubject';
import { Subject } from 'rxjs';
import { take, takeUntil } from 'rxjs/operators';


export class DropdownValue {
  id:string;
  description :string;

  constructor(id:string,description:string) {
    this.id = id;
    this.description = description;
  }
}

@Component({
  selector: 'app-select',
  templateUrl: './select.component.html'
})
export class SelectComponent implements OnInit, OnDestroy, AfterViewInit  {

  @Input()  list : DropdownValue[];
  @Input() dropDownPlaceHolder :string;
  @Input() noDataFoundLabel :string;

  @Input() defaultId :string;
  @Input() defaultDescription :string;
  
  @Output()  select: EventEmitter<any>;

  

  
  /** control for the selected bank */
  public dropDownCtrl: FormControl = new FormControl();

  /** control for the MatSelect filter keyword */
  public dropDownFilterCtrl: FormControl = new FormControl();

  

  /** list of banks filtered by search keyword */
  public filteredList: ReplaySubject<any[]> = new ReplaySubject<any[]>(1);

  @ViewChild('singleSelect') singleSelect: MatSelect;


  /** Subject that emits when the component has been destroyed. */
  private _onDestroy = new Subject<void>();

  
  constructor() {  this.select = new EventEmitter();}

  // Onselect change Event 
  changeValue($event: EventEmitter<MatSelectChange>) {
    this.select.emit($event);
      }

  ngOnInit() {

    // load the initial bank list
    this.filteredList.next(this.list.slice());

    // listen for search field value changes
    this.dropDownFilterCtrl.valueChanges
      .pipe(takeUntil(this._onDestroy))
      .subscribe(() => {
        this.filterLists();
      });
  }

  ngAfterViewInit() {
    this.setInitialValue();
  }

  ngOnDestroy() {
    this._onDestroy.next();
    this._onDestroy.complete();
  }

  
  /**
   * Sets the initial value after the filteredList are loaded initially
   */
  private setInitialValue() {
    this.filteredList
      .pipe(take(1), takeUntil(this._onDestroy))
      .subscribe(() => {
        // setting the compareWith property to a comparison function
        // triggers initializing the selection according to the initial value of
        // the form control (i.e. _initializeSelection())
        // this needs to be done after the filteredList are loaded initially
        // and after the mat-option elements are available
        this.singleSelect.compareWith = (a: any, b: any) => a.id === b.id;
      });
  }

  private filterLists() {
    if (!this.list) {
      return;
    }
    // get the search keyword
    let search = this.dropDownFilterCtrl.value;
    if (!search) {
      this.filteredList.next(this.list.slice());
      return;
    } else {
      search = search.toLowerCase();
    }
    // filter the list
    this.filteredList.next(
      this.list.filter(x => x.description.toLowerCase().indexOf(search) > -1)
    );
  }

}
`
thanx you for your help

**Comment by OmarAlBchouti** [comment] 2018-07-04 17:38
I manage to add a live demo find in the zip file as mp4 video
[DropDownFilterDemo.zip](https://github.com/bithost-gmbh/ngx-mat-select-search/files/2164013/DropDownFilterDemo.zip)

**Comment by macjohnny** [comment] 2018-07-05 06:46
I am closing this as it is not a bug of `ngx-mat-select-search`, but rather of the component that uses it.
@OmarAlBchouti feel free to open another issue if you find anything else.

**Closed by macjohnny** 2018-07-05 06:46 UTC
Labels: bug, question

**Comment by OmarAlBchouti** [comment] 2018-07-05 07:32
Yup, that solved my problem thank you for your help.

**Comment by macjohnny** [comment] 2018-07-05 07:36
@OmarAlBchouti glad I could help. don't forget to star `ngx-mat-select-search` on Github if you like the project ;-)
![image](https://user-images.githubusercontent.com/5589029/42308751-cddd2c1e-8036-11e8-9ddd-2dc2346e6bf2.png)

**Comment by SanjanaRajasekar** [comment] 2021-06-27 13:47
Can you please help me to solve how to set the default values to ngx-mat-select-search 'multiselect' dropdown ?

**Comment by macjohnny** [comment] 2021-06-28 05:56
@SanjanaRajasekar please open a new issue with a demo

**Comment by pravallikag12** [comment] 2022-09-16 22:03
@macjohnny 
Can you please look into the below similar issue: 
https://github.com/bithost-gmbh/ngx-mat-select-search/issues/391
