### ISSUE TITLE
[BUG] MultiSelectedValues are lost if previousValue has not been empty

### ISSUE THREAD

**Issue by broekema41** [bithost-gmbh/ngx-mat-select-search#279] opened 2020-11-13 14:47 UTC
**Describe the bug**
MultiSelectedValues are lost if previousValue has not been empty.

**To Reproduce**
 The Germany Banks are no longer in the selection.

**Expected behavior**
Bank J (Italy) should be added to all the Germany banks

**Screenshots**
![peek](https://user-images.githubusercontent.com/4007585/99084597-749b8180-25c7-11eb-9ecb-ac7826da1525.gif)

**Desktop (please complete the following information):**

**Additional context**
Working on a pull request for your review.

**Comment by macjohnny** [comment] 2020-11-13 15:04
@broekema41 thanks for reporting. would you like to fix this?

**Comment by broekema41** [comment] 2020-11-15 11:09
hello @macjohnny,

Pull request is open for your review. If you have any question, remarks do not hesitate to ask.

kind regards,
Roland

**Comment by macjohnny** [comment] 2020-11-16 10:20
@broekema41 your fix was released with version 3.1.3

**Comment by Daishy** [comment] 2020-11-17 12:09
@macjohnny @broekema41 
Hi :)
i'm just updating an app to angular 11 and bumbed the ngx-mat-select-search version from 3.0.3 to 3.1.3. With the new version I get null-references-failures, because `this.matSelect.ngControl` is null. This seems to be caused by the changes in `mat-select-search.component.ts`s `initMultipleHandling`. The previous access was just `this.matSelect.xxx` and the commit changed it to `this.matSelect.ngControl.xxx`. I reverted back to 3.0.3 and that versions works with angular 11. 
I haven't gotten the time yet to produce a minimal example to check, if i can reproduce the problem in a minimal environment though. 

best regards

**Closed** 2020-11-17 12:30 UTC
Labels: bug
