### ISSUE TITLE
[BUG] No Input field in connection with ngx-translate

### ISSUE THREAD

**Issue by untouch** [bithost-gmbh/ngx-mat-select-search#350] opened 2021-12-15 10:50 UTC
There is no Inputfield in connection with using ngx-translate.

Using:
Angular v10.0.3
ngx-mat-select-search v3.3.3
ngx-translate v13.0.0

**Comment by macjohnny** [comment] 2021-12-15 11:07
Can you please give some more details, code examples and a reproduction?

**Comment by macjohnny** [comment] 2022-02-04 16:10
closing due to the lack of information.
Feel free to provide more information, so I could reopen the bug

**Closed by macjohnny** 2022-02-04 16:10 UTC
Labels: bug
