### ISSUE TITLE
what is the issue with 08-infinite-scroll-example from stackblitz

### ISSUE THREAD

**Issue by NitinMagdum** [bithost-gmbh/ngx-mat-select-search#243] opened 2020-07-29 13:25 UTC
i am using this plugin for infinite scroll and search functionality but its not working.

https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?spm=a2c6h.14275010.0.0.4843743e0qwXH3&file=src%2Fapp%2Fapp.component.html

**Comment by macjohnny** [comment] 2020-07-29 17:26
@NitinMagdum can you please describe the expected behavior and the actual/current behavior?

**Comment by NitinMagdum** [comment] 2020-07-29 18:14
Current Behavior - only showing 20 items till Bank 19 but the total number of records are 1000
mockBankList = Array.from({ length: 1000 }).map((_, i) => `Bank ${i}`);

Expected behavior - when we scroll till the bottom it should load next set of 20 records(limit is 20 so it should show total 40 recors and so on), i think it is not calling getNextBatch
check this example -https://stackblitz.com/edit/ng-mat-select-infinite-scroll (scroll it will load next set of records here limit is 10)
the problem in this package(ng-mat-select-infinite-scroll) is there is no search box

**Comment by NitinMagdum** [comment] 2020-07-30 04:32
i added both ngx-mat-select-search and  ng-mat-select-infinite-scroll
https://stackblitz.com/edit/ng-mat-select-infinite-scroll-3gsd97?file=src%2Fapp%2Fapp.component.ts
but here the issue i am facing is after Option 9 any option i select it is not getting set to the select input box

**Comment by NitinMagdum** [comment] 2020-07-30 05:39
it would be great if you provide working example with any of the below package for infinite scroll
ngx-infinite-scroll
ng-mat-select-infinite-scroll
cdk-virtual-scroll-viewport

**Comment by macjohnny** [comment] 2020-08-04 12:07
the example seems to be broken
would you like to fix it?

**Comment by macjohnny** [comment] 2020-08-04 16:33
the example is fixed now (https://github.com/bithost-gmbh/ngx-mat-select-search-example/commit/93794534266d5bf0dd61cbbe75ba21935c6875a5)

see https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fexamples%2F08-infinite-scroll-example%2Finfinite-scroll-example.component.html

**Comment by macjohnny** [comment] 2020-08-05 08:29
@NitinMagdum 

> i added both ngx-mat-select-search and ng-mat-select-infinite-scroll
> https://stackblitz.com/edit/ng-mat-select-infinite-scroll-3gsd97?file=src%2Fapp%2Fapp.component.ts
> but here the issue i am facing is after Option 9 any option i select it is not getting set to the select input box

you need to make sure that the selected options are always in the list of actually displayed options, otherwise the cannot be shown as a selected value

**Comment by NitinMagdum** [comment] 2020-08-06 12:24
@macjohnny  - same issue what i mentioned above i am able to select till Bank 19 after that if i select anything its not adding the value to select box

**Comment by macjohnny** [comment] 2020-08-06 12:46
did you consider https://github.com/bithost-gmbh/ngx-mat-select-search/issues/243#issuecomment-669058768 ?

**Comment by NitinMagdum** [comment] 2020-08-06 13:17
https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fexamples%2F08-infinite-scroll-example%2Finfinite-scroll-example.component.html

same issue what i mentioned above i am able to select till Bank 19 after that if i select anything its not adding the value to select box

your reply - you need to make sure that the selected options are always in the list of actually displayed options, otherwise the cannot be shown as a selected value (how to achieve this )

**Closed** 2020-08-10 07:49 UTC
Labels: bug

**Comment by NitinMagdum** [comment] 2020-08-11 06:41
@macjohnny -- facing one more issue 

how to reproduce
1 - click select box scroll for some time select a value remove focus from select by clicking outside the box
2 -  then again click on select box dont do anything click outside the existing selected value is not getting attached to the box

verify the behavior with single selection example 1, here its working correctly after above step 2 the selected value in step 1 will be remain selected in the box

**Comment by macjohnny** [comment] 2020-08-11 06:53
@NitinMagdum please open a new issue with exact reproduction steps (I didn't understand how to reproduce your issue)
