### ISSUE TITLE
Select all checkbox will not be unselected once the ngx-mat-select-search control is reset.

### ISSUE THREAD

**Issue by ShipraNanaiah** [bithost-gmbh/ngx-mat-select-search#219] opened 2020-03-05 07:22 UTC
I've used ngx-mat-select-search multiselect control having search feature. When a toggleSelectAll() method is called, all the items in the drop down are selected. After saving the items from the dropdown on click of save button, ngx-mat-select-search control reset() method is called to uncheck all the previously selected items. It unchecks the entire dropdown as expected, but the SELECT ALL check box remains checked. Ideally, the reset method should uncheck the select checkbox as well which is not working for me. Could some one please let me know the fix for this issue? Thanks.
![image](https://user-images.githubusercontent.com/61820710/75957450-0d79e900-5ee0-11ea-8330-930500853286.png)

**Comment by macjohnny** [comment] 2020-03-05 07:34
duplicate of https://github.com/bithost-gmbh/ngx-mat-select-search/issues/189

**Closed by macjohnny** 2020-03-05 07:34 UTC

**Comment by ShipraNanaiah** [comment] 2020-03-05 09:52
@macjohnny , Thanks for the sharing solution link. But I tried passing it as an input parameter and no luck. I also tried setting the **this.toggleAllCheckboxChecked = false;**  in the button click event. Is there something I'm missing here please?

**Comment by macjohnny** [comment] 2020-03-05 10:05
you need to set the state of the checkbox toggle as an input
```
<ngx-mat-select-search [toggleAllCheckboxChecked]="isToggleAllChecked">
```
and in your component you need to add some logic to set `isToggleAllChecked` to true or false, depending on the selected options.

**Comment by HabelC** [comment] 2021-08-20 09:20
I set the toggleAllCheckboxChecked and also check its state, but nevertheless it does not work. Please follow my bug description.
