### ISSUE TITLE
[BUG] moving search input when i scroll mat-select + ngx-mat-select-search on IOS

### ISSUE THREAD

**Issue by drytikov** [bithost-gmbh/ngx-mat-select-search#132] opened 2019-03-28 10:27 UTC
When I scroll the select on ios, search input is moving. It will be good, if it will be fixed. [Video(DEMO)](https://youtu.be/WVa_e5f_W_g)

**Comment by macjohnny** [comment] 2019-03-28 11:21
it seems that https://github.com/bithost-gmbh/ngx-mat-select-search/issues/70 occurs again, as stated in https://github.com/bithost-gmbh/ngx-mat-select-search/pull/88#issuecomment-472099198

@drytikov could you help me find a fix for this?

**Comment by macjohnny** [comment] 2019-03-28 12:35
cc @pheliperocha

**Comment by macjohnny** [comment] 2019-03-28 12:39
it looks like the problem is much less visible as opposed to #70. unfortunately, I couldn't find a solution that completely fixes the issue. so for now, I just leave this minor issue open, maybe someone has an idea.
in google chrome it scrolls seamlessly.

**Comment by macjohnny** [comment] 2024-03-18 09:23
this seems to be fixed with [version 7.0.0](https://github.com/bithost-gmbh/ngx-mat-select-search/releases/tag/7.0.0)

**Closed by macjohnny** 2024-03-18 09:23 UTC
Labels: bug, minor
