### ISSUE TITLE
Using a WAI-ARIA role to expose the role of a user interface component

### ISSUE THREAD

**Issue by VanonckelenDieter** [bithost-gmbh/ngx-mat-select-search#287] opened 2020-12-07 10:25 UTC
Hello,

I am using your component in my project and its performing well, thanks for that.

The only thing I noticed is that your component is not met with the success criteria of the accessibility guidelines AA because the elements are missing a 'role' attribute.

Maybe to make your component more attractive for government usage and make it more accessible for people with disabilities you can update this so it does not fail the AA requirements that are set by the European unions law for all government websites and web applications.

Ill drop the warning as an attached file.
![Role](https://user-images.githubusercontent.com/37801224/101339527-d83f6480-387e-11eb-9c9f-03dedbaab41b.PNG)

Thanks in advance!

**Comment by macjohnny** [comment] 2020-12-07 11:19
Closing as a duplicate of https://github.com/bithost-gmbh/ngx-mat-select-search/issues/286
@VanonckelenDieter would you like to fix it?

**Closed by macjohnny** 2020-12-07 11:19 UTC
