### ISSUE TITLE
Search is not working with dynamic data

### ISSUE THREAD

**Issue by shaukath** [bithost-gmbh/ngx-mat-select-search#204] opened 2020-01-08 04:12 UTC
Loading dynamic data on scroll to mat options , in this scenario search is not working.

If I change the data randomly then also search is not working.

**Comment by macjohnny** [comment] 2020-01-08 05:34
Can you please provide an example?

**Comment by shaukath** [comment] 2020-01-08 13:28
Add some data to mat options, while scrolling I am pushing some more data to same options array after that search is not working

**Comment by macjohnny** [comment] 2020-01-08 13:52
I think this is a duplicate of https://github.com/bithost-gmbh/ngx-mat-select-search/issues/200
Please continue the discussion there.
A contribution/fix would be appreciated.

**Closed by macjohnny** 2020-01-08 13:52 UTC
Labels: bug
