### ISSUE TITLE
search is not working when loading data dynamically using infinite scroll

### ISSUE THREAD

**Issue by vashi538** [bithost-gmbh/ngx-mat-select-search#205] opened 2020-01-08 16:07 UTC
ngx-mat-select-search is not giving any results when using with msInfiniteScroll

**Comment by macjohnny** [comment] 2020-01-08 16:15
duplicate of https://github.com/bithost-gmbh/ngx-mat-select-search/issues/200
please continue the discussion there.
@vashi538 a fix/contribution would be appreciated.

**Comment by macjohnny** [comment] 2020-01-08 16:16
please provide an example and more information

**Comment by vashi538** [comment] 2020-01-08 16:25
I'm using mat-select with ngx-mat-select-search and I have 2000 records in mat-options it's giving performance issue  so now  I'm using msInfiniteScroll (infiniteScroll)="getNextBatch() .when I use msInfiniteScroll, ngx-mat-select-search is not working

**Comment by macjohnny** [comment] 2020-01-08 16:44
It would be very helpful if you could provide a stackblitz example
See https://raw.githubusercontent.com/bithost-gmbh/ngx-mat-select-search/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by macjohnny** [comment] 2020-01-21 06:31
@vashi538 could you please provide an example to make it easier for someone to help you?

**Comment by L-NiNo** [comment] 2020-02-06 16:05
@macjohnny @vashi538 
I was able to get the search to work with infinite scroll
https://stackblitz.com/edit/mat-select-search-with-infinity-scroll

**Comment by macjohnny** [comment] 2020-02-06 16:37
@L-NiNo thanks for sharing your solution. so I think we can close this issue

**Closed by macjohnny** 2020-02-06 16:37 UTC
