### ISSUE TITLE
ngx-mat-select-search not updating width on resize

### ISSUE THREAD

**Issue by mhosman** [bithost-gmbh/ngx-mat-select-search#81] opened 2018-10-31 01:09 UTC
If you keep the mat-select-search opened and you resize the page, the mat-select-search is not being resized.

**Comment by maechler** [comment] 2018-11-09 06:51
@mhosman Thanks for reporting! I could not yet reproduce that issue. Do you mean that the select box can be wider than the viewport if the viewport gets very small?
Can you please check whether this also happens to `mat-select` if you use it without `ngx-mat-select-search`?

**Comment by macjohnny** [comment] 2018-11-20 11:17
I can't reproduce the issue either, so I am closing this issue.
@mhosman please provide a screenshot / demo of the situation you describe, so I will reopen the issue to investigate it again.

**Comment by macjohnny** [comment] 2018-11-23 11:18
@mhosman the issue you described can occur if the panel is resized (which I could not observe in the default setup) due to the following line:

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts#L429

One solution would be to manually invoke the `getWidth()` method once the resize event occurs. For this, the access of `getWidth()` would need to be changed to `public`.
Would this help you?

**Comment by macjohnny** [comment] 2019-01-24 07:56
this should be fixed due to https://github.com/angular/material2/pull/14932

**Closed** 2019-03-21 16:11 UTC

**Comment by macjohnny** [comment] 2019-03-21 16:44
this is released in `1.7.0`
