### ISSUE TITLE
sets to first option after selection

### ISSUE THREAD

**Issue by pravallikag12** [bithost-gmbh/ngx-mat-select-search#391] opened 2022-09-16 21:43 UTC
Bug:
 when I filter the drop-down then select an item, the item is selected, then in a moment the drop-down select the first value

https://user-images.githubusercontent.com/14279600/190794396-afaab44d-22f2-40f7-ab75-d3f49b545582.mp4

Code

HTML:
```html
                                  <mat-form-field>
                                    <mat-select [formControl]="shipToCtrl" #singleSelect>
                                      <mat-option>
                                        <ngx-mat-select-search [formControl]="shipToFilter" placeholderLabel="Find..." 
                                        noEntriesFoundLabel="'no matching found'"></ngx-mat-select-search>
                                      </mat-option>
                                      <mat-option *ngFor="let select of filteredShipTo | async" value="select"> {{
                                        select.name }}
                                      </mat-option>
                                    </mat-select>
                                  </mat-form-field>
                                  <p>
                                    Selected Option: {{shipToCtrl.value?.name}}
                                  </p>
```

TS:
```typescript
  /** list of ShipTO */
  protected shipTo: ShipToList[] = this.workOrderCustomerList;

  /** control for the selected ShipTO */
  public shipToCtrl: FormControl = new FormControl();

  /** control for the MatSelect filter keyword */
  public shipToFilter: FormControl = new FormControl();

  /** list of ShipTo filtered by search keyword */
  public filteredShipTo: ReplaySubject<ShipToList[]> = new ReplaySubject<ShipToList[]>(1);

  @ViewChild('singleSelect', { static: true }) singleSelect: MatSelect;

  /** Subject that emits when the component has been destroyed. */
  protected _onDestroy = new Subject<void>();

  ngOnInit() {
    // set initial selection
    this.shipToCtrl.setValue(this.shipTo);

    // load the initial bank list
    this.filteredShipTo.next(this.shipTo.slice());

    // listen for search field value changes
    this.shipToFilter.valueChanges
      .pipe(takeUntil(this._onDestroy))
      .subscribe(() => {
        this.filteredShipToCtrl();
      });
  }

  ngAfterViewInit() {
    this.setInitialValue();
  }

  ngOnDestroy() {
    this._onDestroy.next();
    this._onDestroy.complete();
  }

  /**
   * Sets the initial value after the filteredBanks are loaded initially
   */
  protected setInitialValue() {
    this.filteredShipTo
      .pipe(take(1), takeUntil(this._onDestroy))
      .subscribe(() => {
        // setting the compareWith property to a comparison function
        // triggers initializing the selection according to the initial value of
        // the form control (i.e. _initializeSelection())
        // this needs to be done after the filteredBanks are loaded initially
        // and after the mat-option elements are available
        this.singleSelect.compareWith = (a: ShipToList, b: ShipToList) => a && b && a.name === b.name;
      });
  }

  protected filteredShipToCtrl() {
    if (!this.shipTo) {
      return;
    }
    // get the search keyword
    let search = this.shipToFilter.value;
    if (!search) {
      this.filteredShipTo.next(this.shipTo.slice());
      return;
    } else {
      search = search.toLowerCase();
    }
    // filter the banks
    this.filteredShipTo.next(
      this.shipTo.filter(id => id.name.toLowerCase().indexOf(search) > -1)
    );
  }
```

I tried commenting the below line - that did not work too

    // set initial selection
    this.shipToCtrl.setValue(this.shipTo);

**Comment by AhsanAyaz** [comment] 2022-10-09 10:27
@pravallikag12 this doesn't seem to happen within this repository's examples. Do you think it could be due to this?
```ts
  public filteredShipTo: ReplaySubject<ShipToList[]> = new ReplaySubject<ShipToList[]>(1);
```

**Comment by macjohnny** [comment] 2024-03-18 09:20
oops forgot to reply on this one. closing for now, please comment if you think this is an issue in ngx-mat-select-search itself, since @AhsanAyaz confirmed it doesnt happen with the example code.

**Closed by macjohnny** 2024-03-18 09:20 UTC
Labels: bug
